### ISSUE TITLE
UnknownError

### ISSUE THREAD

**Issue by Jeff-14159** [thgreasi/localForage-setItems#6] opened 2016-12-06 23:15 UTC
I'm using setItems like so:

`store.setItems(itemsToStore, null, null, function (err) {`
` ` ` if (err) {`
` ` ` ` `console.log('Error!!! function: lsSetItems {.....message: ', store, itemsToStore, err);`
` ` `} else {`
` ` ` ` `completedSuccess(true);`
` ` `}`
`});`

i'm passing in  an object whos keys are uuids, i'm doing this for multiple tables/stores with out fail however on one store I get an error...

it returns an "object IDBTransaction"

IDBTransaction.error {
name "UnknownError"
mode "readwrite"
READ_ONLY "readonly"
READ_WRITE "readwrite"
VERSION_CHANGE "versionchange"

 the data it a little bit large.. maybe 5 MB among 7 keys?  Before I was setting each one, one at a time so I don't think I I'm ran out of space on localstorage any ideas on how to trouble shoot this further?

IE: 11.447
LocalForage: 1.3.0
SetItems: 1.3.1

Thanks,
Jeff

**Comment by Jeff-14159** [comment] 2016-12-07 00:22
update:  I seemed to have a workaround for this error for now by making sure to call the setItems synchronously, making sure the last one has completed before calling it again on a different store.... *sigh* a promise or callback issue???

believe this might be a bug in the underlying localforage driver, I had the same issue when first initializing multiple stores, if I did it to fast they would error out. I had to make a custom looper function for that as well.

**Comment by thgreasi** [comment] 2016-12-07 05:27
Can you try updating localforage to v1.4 and check again? You will probably not face any from the upgrade. Also, can you replicate on other browsers? Even better, can you provide a sample codepen based on the provided examines that replicates the issue?

**Comment by thgreasi** [comment] 2017-01-15 10:50
Any feedback on this?

**Comment by Jeff-14159** [comment] 2017-01-16 15:41
sorry been busy with end of year and new product release.... will try and put together a code pen for you in the next couple days.

Thanks,
Jeff

**Comment by Jeff-14159** [comment] 2017-01-27 21:29
I finally got some time to put together a code pen... this has been happening when I initialize local storage and when doing setItems **IF** doing more than one at a time by starting another one before the last has completed...

```
var ls = {store1:'', store2:'', etc...}
  $.each(ls, function(storeName, lsInstance){   
    ls[storeName] = localforage.createInstance({
                  driver: [localforage.INDEXEDDB, localforage.WEBSQL,localforage.LOCALSTORAGE],   
                  name: 'testApp',
                  storeName: storeName
    });
  });
```
http://codepen.io/Jeff-14159/pen/KayzEp

since moving to windows 10 I've not seen that issue... and I think the code pen site is a little slow.... so maybe try this on your local system? but looks like reproducing will be a little hard as it is random. so close this issue if you want I've found a decent workaround that will ensure this wont happen.

Thanks,
Jeff

**Comment by thgreasi** [comment] 2017-01-28 11:00
@Jeff-14159 Thanks for this super detailed report :+1: I see that you did put a great effort on this.
I was not able to reproduce the issue using the provided on FF & Chrome, but I will give it a try on IE & Edge on Monday.

**Comment by thgreasi** [comment] 2017-01-30 08:46
@Jeff-14159 Using the provided codepen, I was not able to reproduce neither on Edge not on IE 11 & 10.
Following your suggestion I'm closing this for now.
Please reopen if anything new comes up.
Once again, thanks for your effort on tracking this issue.

**Closed as completed by thgreasi** 2017-01-30 08:46 UTC
